spring.application.name=bunker

spring.datasource.url=jdbc:postgresql://localhost:5432/bunker_online
spring.datasource.username=spring_user
spring.datasource.password=1488

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MTY5M2M3ZGEtY2Y0OC00Y2VjLTg2YzYtYmU0Zjg0ZTkxMzljCg==
jwt.expiration=86400000