CREATE TABLE IF NOT EXISTS profession_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS experience_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS characteristic_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uq_characteristic_type_value UNIQUE (type, value)
);

INSERT INTO profession_catalog (value, description) VALUES
    ('Инженер', 'Проектирует и чинит системы'),
    ('Медик', 'Оказывает первую помощь в полевых условиях'),
    ('Повар', 'Готовит из ограниченных ресурсов'),
    ('Механик', 'Ремонтирует оборудование и генераторы')
ON CONFLICT (value) DO NOTHING;

INSERT INTO experience_catalog (value) VALUES
    ('6 месяцев'),
    ('1 год'),
    ('2 года'),
    ('3 года'),
    ('5 лет')
ON CONFLICT (value) DO NOTHING;

INSERT INTO characteristic_catalog (type, value, description) VALUES
    ('health', 'Астма', 'Нужен ингалятор при нагрузке'),
    ('health', 'Крепкое здоровье', 'Серьезных ограничений нет'),
    ('hobby', 'Рыбалка', 'Может добывать еду вблизи водоемов'),
    ('hobby', 'Радиолюбитель', 'Понимает простую связь и пайку'),
    ('character', 'Спокойный', 'Снижает конфликты в группе'),
    ('character', 'Лидер', 'Берет ответственность в критической ситуации'),
    ('phobia', 'Клаустрофобия', 'Тяжело переносит закрытые пространства'),
    ('phobia', 'Боязнь темноты', 'Нужен источник света для стабильности'),
    ('info', 'Знает план эвакуации', 'Быстро ориентируется в укрытии'),
    ('info', 'Базовые знания медицины', 'Может помочь до прихода медика'),
    ('baggage', 'Набор инструментов', 'Полезен для ремонта'),
    ('baggage', 'Аптечка', 'Есть базовые медикаменты'),
    ('cards', 'Обмен местами', 'Можно поменяться местами с игроком'),
    ('cards', 'Раскрыть характеристику', 'Открывает случайную характеристику оппонента')
ON CONFLICT (type, value) DO NOTHING;
